remote_theme: jekyll/minima
title: CS322
description: "Notes and bits and things"
show_excerpts: true
minima:
  skin: dark


plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
